---
# Raspberry Pi specific overrides with optimized resource limits for ARM hardware

x-pi-resource-limits: &pi-resource-limits
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 64M

x-pi-core-resource-limits: &pi-core-resource-limits
  deploy:
    resources:
      limits:
        memory: 512M
        cpus: "0.8"
      reservations:
        memory: 128M
        cpus: "0.2"

x-pi-light-resource-limits: &pi-light-resource-limits
  deploy:
    resources:
      limits:
        memory: 128M
      reservations:
        memory: 32M

services:
  ovos_messagebus:
    <<: *pi-resource-limits
    healthcheck:
      disable: true

  ovos_phal:
    <<: *pi-resource-limits
    healthcheck:
      disable: true
    group_add:
      - "${GPIO_GID}"
      - "${I2C_GID}"
      - "${SPI_GID}"

  ovos_phal_admin:
    <<: *pi-light-resource-limits
    healthcheck:
      disable: true
    group_add:
      - "${GPIO_GID}"
      - "${I2C_GID}"
      - "${SPI_GID}"

  ovos_listener:
    <<: *pi-resource-limits
    healthcheck:
      disable: true

  ovos_plugin_ggwave:
    <<: *pi-resource-limits
    healthcheck:
      disable: true

  ovos_audio:
    <<: *pi-resource-limits
    healthcheck:
      disable: true

  ovos_core:
    <<: *pi-core-resource-limits
    healthcheck:
      disable: true
    group_add:
      - "${GPIO_GID}"
      - "${I2C_GID}"
      - "${SPI_GID}"

  ovos_cli:
    <<: *pi-light-resource-limits
    healthcheck:
      disable: true
