name: Sync Compose Directory

on:
  schedule:
    # Runs at 2:00 UTC every day; adjust as needed
    - cron: "0 2 * * *"
  workflow_dispatch: # allows manual trigger

jobs:
  sync-compose:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - name: Checkout benedikta-ovos
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Sync compose from ovos-docker
        run: |
          # Make the sync script executable
          chmod +x ./update-sync-ovos-compose.sh
          # Run the script
          ./update-sync-ovos-compose.sh

      - name: Commit & push changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: "compose"
          message: "Update compose/ from ovos-docker:dev"
          push: true
