name: Renovate

on:
  schedule:
    - cron: "0/30 * * * *"
  workflow_dispatch:

env:
  RENOVATE_VERSION: "41.165.7"

jobs:
  renovate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Renovate Run
        env:
          DOCKER_HOST: tcp://dockerproxy:2375
          RENOVATE_PLATFORM: gitea
          RENOVATE_ENDPOINT: https://git.trez.wtf/api/v1
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_BOT_TOKEN }}
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_TOKEN }}
          RENOVATE_CONFIG_FILE: renovate.json
          RENOVATE_REPOSITORIES: trez/benedikta-ovos
          RENOVATE_HOST_RULES: |
            [
              {
                "description": "Docker Hub authentication",
                "hostType": "docker",
                "matchHost": "docker.io",
                "username": "${{ secrets.DOCKERHUB_USER }}",
                "password": "${{ secrets.DOCKERHUB_PASSWORD }}"
              },
              {
                "description": "GitHub Container Registry (GHCR)",
                "hostType": "docker",
                "matchHost": "ghcr.io",
                "username": "${{ secrets.GHCR_USER }}",
                "password": "${{ secrets.GHCR_LOGIN_TOKEN }}"
              },
              {
                "description": "Self-hosted Gitea Docker Registry",
                "hostType": "docker",
                "matchHost": "git.trez.wtf",
                "username": "${{ secrets.BOT_GITEA_USER }}",
                "password": "${{ secrets.BOT_GITEA_PASSWORD }}"
              }
            ]
        run: |
          docker run --rm \
            -e RENOVATE_PLATFORM \
            -e RENOVATE_ENDPOINT \
            -e RENOVATE_TOKEN \
            -e LOG_LEVEL \
            -e RENOVATE_GITHUB_COM_TOKEN \
            -e RENOVATE_CONFIG_FILE \
            -e RENOVATE_REPOSITORIES \
            -e RENOVATE_HOST_RULES \
            --volumes-from ${{ env.JOB_CONTAINER_NAME }} \
            -w ${GITHUB_WORKSPACE} \
            renovate/renovate:${{ env.RENOVATE_VERSION }}-full
