---
x-podman: &podman
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "200m"
    max-file: "1"

x-common-environment: &common-environment
  TZ: ${TZ:-UTC}

x-light-resource-limits: &light-resource-limits
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 64M

x-hivemind-base: &hivemind-base
  <<: [*podman, *light-resource-limits]
  restart: unless-stopped
  logging: *default-logging
  pull_policy: ${PULL_POLICY:-always}
  tty: true
  environment:
    <<: *common-environment
  network_mode: host
  volumes:
    - ${HIVEMIND_CONFIG_FOLDER}:/home/${HIVEMIND_USER}/.config/hivemind:z
    - ${HIVEMIND_SHARE_FOLDER}:/home/${HIVEMIND_USER}/.local/share/hivemind:z
  healthcheck:
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 15s

services:
  hivemind_listener:
    <<: *hivemind-base
    container_name: hivemind_listener
    hostname: hivemind_listener
    image: docker.io/smartgic/hivemind-listener:${VERSION}
    depends_on:
      ovos_core:
        condition: service_started
    healthcheck:
      test: ["CMD", "pgrep", "-f", "hivemind-listener"]

  hivemind_cli:
    <<: *hivemind-base
    container_name: hivemind_cli
    hostname: hivemind_cli
    image: docker.io/smartgic/hivemind-cli:${VERSION}
    depends_on:
      hivemind_listener:
        condition: service_started
