---
x-podman: &podman
  userns_mode: keep-id
  security_opt:
    - "label=disable"

x-logging: &default-logging
  driver: json-file
  options:
    mode: non-blocking
    max-buffer-size: 4m
    max-size: "200m"
    max-file: "1"

x-common-environment: &common-environment
  TZ: ${TZ:-UTC}

x-skill-resource-limits: &skill-resource-limits
  deploy:
    resources:
      limits:
        memory: 256M
      reservations:
        memory: 64M

x-skill-base: &skill-base
  <<: [*podman, *skill-resource-limits]
  restart: unless-stopped
  logging: *default-logging
  pull_policy: ${PULL_POLICY:-always}
  environment:
    <<: *common-environment
  network_mode: host
  volumes:
    - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
    - ${TMP_FOLDER}:/tmp/mycroft
  depends_on:
    ovos_core:
      condition: service_started

volumes:
  ovos_nltk:
    name: ovos_nltk
    driver: local

services:
  ovos_skill_wikipedia:
    <<: *skill-base
    container_name: ovos_skill_wikipedia
    hostname: ovos_skill_wikipedia
    image: docker.io/smartgic/ovos-skill-wikipedia:${VERSION}
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_nltk:/home/${OVOS_USER}/nltk_data
      - ${TMP_FOLDER}:/tmp/mycroft

  ovos_skill_weather:
    <<: *skill-base
    container_name: ovos_skill_weather
    hostname: ovos_skill_weather
    image: docker.io/smartgic/ovos-skill-weather:${VERSION}

  ovos_skill_volume:
    <<: *skill-base
    container_name: ovos_skill_volume
    hostname: ovos_skill_volume
    image: docker.io/smartgic/ovos-skill-volume:${VERSION}

  ovos_skill_date_time:
    <<: *skill-base
    container_name: ovos_skill_date_time
    hostname: ovos_skill_date_time
    image: docker.io/smartgic/ovos-skill-date-time:${VERSION}

  ovos_skill_personal:
    <<: *skill-base
    container_name: ovos_skill_personal
    hostname: ovos_skill_personal
    image: docker.io/smartgic/ovos-skill-personal:${VERSION}

  ovos_skill_fallback_unknown:
    <<: *skill-base
    container_name: ovos_skill_fallback_unknown
    hostname: ovos_skill_fallback_unknown
    image: docker.io/smartgic/ovos-skill-fallback-unknown:${VERSION}

  ovos_skill_hello_world:
    <<: *skill-base
    container_name: ovos_skill_hello_world
    hostname: ovos_skill_hello_world
    image: docker.io/smartgic/ovos-skill-hello-world:${VERSION}

  ovos_skill_alerts:
    <<: *skill-base
    container_name: ovos_skill_alerts
    hostname: ovos_skill_alerts
    image: docker.io/smartgic/ovos-skill-alerts:${VERSION}

  ovos_skill_ggwave:
    <<: *skill-base
    container_name: ovos_skill_ggwave
    hostname: ovos_skill_ggwave
    image: docker.io/smartgic/ovos-skill-ggwave:${VERSION}

  ovos_skill_duckduckgo:
    <<: *skill-base
    container_name: ovos_skill_duckduckgo
    hostname: ovos_skill_duckduckgo
    image: docker.io/smartgic/ovos-skill-duckduckgo:${VERSION}

  ovos_skill_wordnet:
    <<: *skill-base
    container_name: ovos_skill_wordnet
    hostname: ovos_skill_wordnet
    image: docker.io/smartgic/ovos-skill-wordnet:${VERSION}
    volumes:
      - ${OVOS_CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ovos_nltk:/home/${OVOS_USER}/nltk_data
      - ${TMP_FOLDER}:/tmp/mycroft
